# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

 

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """

        mapping={}

        for char in s:

            if char not in mapping:
                mapping[char]=1

            else:
                mapping[char]+=1

        # print(mapping)

        for char in t:
            if char not in mapping:
                return char

            else:
                if mapping[char]==0:
                    return char

                else:
                    mapping[char]-=1

        
